; PlatformIO – SPLIT-NODE (v7)
; Diesen Ordner in VSCode öffnen: File → Open Folder → MTB_Timer_Split
; OTA-Firmware: .pio/build/Split/firmware.bin

[platformio]
src_dir = .

[env:Split]
platform      = espressif32
board         = heltec_wifi_lora_32_V3
framework     = arduino
monitor_speed = 115200

lib_deps =
    jgromes/RadioLib @ ^6.6.0
    olikraus/U8g2    @ ^2.35.19
